# Event Simulator Configuration

# API Configuration
api:
  base_url: "http://localhost:8000"
  events_endpoint: "/api/events"
  # If authentication is needed:
  # auth_token: "your-auth-token-here"

# Simulation Settings
simulation:
  # User IDs to simulate events for
  users:
    - "user_001"
    - "user_002"
    - "user_003"
    - "user_004"
    - "user_005"

  # Event types to generate
  event_types:
    - "mood"
    - "sleep"
    - "exercise"
    - "medication"
    - "social"
    # - "therapy"  # Uncomment to include therapy events
    # - "custom"   # Uncomment to include custom events

  # Interval between batches (in seconds)
  interval_seconds: 5

  # Number of events to generate per batch
  batch_size: 3

  # Event distribution weights (optional - for more realistic patterns)
  weights:
    mood: 30
    sleep: 15
    exercise: 20
    medication: 20
    social: 15

# Historical Data Generation Settings
historical:
  # Number of days of historical data to generate
  days: 7

  # Events per user per day (min, max)
  events_per_day:
    min: 3
    max: 8

  # Time range for events (hours, 24-hour format)
  time_range:
    start_hour: 6
    end_hour: 23

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "simple"  # simple or json
